version: '3.9'

services:
  app:
    container_name: backend-app
    build: ../.
    command: python dog_api/manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"

networks:
  default:
    name: backend
    driver: bridge