version: '3.9'

services:
  db:
    image: postgres:17.5
    env_file: ../.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgres

networks:
  default:
    name: backend
    driver: bridge

volumes:
  pgdata: